name: Production Deployment (karage.co)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_production:
    runs-on: ubuntu-latest
    name: Build and Deploy to Production
    environment:
      name: production
      url: https://karage.co
    env:
      HUGO_VERSION: 0.128.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Verify Hugo Installation
        run: hugo version

      - name: Build Production Site
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --cleanDestinationDir \
            --baseURL "https://karage.co/"

      - name: Deploy to Azure Static Web Apps (Production)
        id: deploy_production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PRODUCTION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "public"
          api_location: ""
          skip_app_build: true

      - name: Production Deployment Complete
        run: |
          echo "✅ Production deployment completed successfully!"
          echo "🌐 Site URL: https://karage.co"
          echo "📅 Deployed at: $(date)"
